apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-core-service
  template:
    metadata:
      labels:
        app: delivery-core-service
    spec:
      hostAliases:
        - ip: "10.60.3.27"
          hostnames:
          - "hl22.zil"
        - ip: "10.60.3.28"
          hostnames:
          - "hl23.zil"
      imagePullSecrets:
        - name: regcred
      containers:
        - name: delivery-core-service
          image: sekretaria/corelab18:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: delivery-config
            - secretRef:
                name: db-credentials
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8080
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"