apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-join-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: delivery-join-service
  template:
    metadata:
      labels:
        app: delivery-join-service
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: delivery-join-service
          image: sekretaria/join18:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          envFrom:
            - configMapRef:
                name: delivery-config
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis-secret
                  key: redis-password
          livenessProbe:
            httpGet:
              path: /healthcheck
              port: 8082
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 2
          readinessProbe:
            httpGet:
              path: /healthcheck
              port: 8082
            periodSeconds: 30
            timeoutSeconds: 3
            failureThreshold: 2
          resources:
            limits:
              cpu: "1"
              memory: "1024Mi"
            requests:
              cpu: "500m"
              memory: "512Mi"